### ISSUE TITLE
1.1.5 - Folders empty

### ISSUE THREAD

**Issue by p33k** [kooohei/brackets-synapse#25] opened 2015-09-10 19:14 UTC
with the latest update 1.1.5 the folders are still empty.
no matter if exclude settings are default or emtpy.

Console shows this:
RemoteManager.js:90 ptn = ^.$ file = backup RexExp = /^.$/ match = null
RemoteManager.js:90 ptn = ^..$ file = backup RexExp = /^..$/ match = null
RemoteManager.js:90 ptn = ^..+$ file = backup RexExp = /^..+$/ match = backup
RemoteManager.js:90 ptn = ^.$ file = cgi-bin RexExp = /^.$/ match = null
RemoteManager.js:90 ptn = ^..$ file = cgi-bin RexExp = /^..$/ match = null
RemoteManager.js:90 ptn = ^..+$ file = cgi-bin RexExp = /^..+$/ match = cgi-bin
....

**Comment by kooohei** [comment] 2015-09-10 19:46
mmm, wierd. however log shows the normal and file list is downloaded.
so that setting is FTP connect?

**Comment by kooohei** [comment] 2015-09-10 19:56
Can you launch app with only enable a brackets-synapse?
It still show error then clicke to the elements tab in the developer tool,
and find node "div" with id is the "synapse-tree".
I want to know whether it is how to。

**Comment by p33k** [comment] 2015-09-10 20:14
Screenshots with : ^.$, ^..$, ^..+$ (not even folders are showed)
Screenshot without exclusions (folders but no files) <ul> lists are empty
![elements without exclusions](https://cloud.githubusercontent.com/assets/6191925/9799719/54da71a8-5809-11e5-8083-ca74417abdc8.PNG)
![elements](https://cloud.githubusercontent.com/assets/6191925/9799724/5c610ae0-5809-11e5-82fc-6ff93fe83f22.PNG)

**Comment by kooohei** [comment] 2015-09-10 20:22
Please find the file. (Help > Show Extensions Folder > user > brackets-synapse > modules > RemoteManager.js)
and rename to RemoteManager.js-bak something...
then replace to  [this]("https://kooohei.github.io/RemoteManager.js" from that.

this is with out exclude function version.
I hope the reason will be found ><

**Comment by p33k** [comment] 2015-09-10 20:26
thanks very much, it works :+1:  :)
what was the mistake? 
keep up the good work, great extension

**Comment by kooohei** [comment] 2015-09-10 20:32
no yet >< we found the reason of problem 

downloaded file is just commented 2lines, that is same function
"//list = getListIgnoreExclude(serverSetting, list);"
bug lives here.

I should be fixed this function.
however, Maybe it also I think to function without problems now of state。
I find the cause, and then the also contact when it was repaired.
please wait moment.

Thanks for above all understand my terrible English.

**Closed** 2015-09-10 21:16 UTC
